# Generated by Django 3.1.7 on 2024-04-21 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaqueteTuristico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('incluye', models.TextField()),
                ('no_incluye', models.TextField()),
                ('disponibles', models.PositiveIntegerField()),
                ('imagen', models.ImageField(upload_to='ruta/donde/guardar/imagenes/')),
            ],
        ),
    ]
