# Generated by Django 3.1.7 on 2024-04-21 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_remove_paqueteturistico_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paqueteturistico',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='paqueteturistico',
            name='fecha_inicio',
        ),
    ]
