# Generated by Django 3.1.7 on 2024-04-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_paqueteturistico_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paqueteturistico',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
    ]
