# Generated by Django 3.1.7 on 2024-04-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_auto_20240423_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paqueteturistico',
            name='imagen',
            field=models.ImageField(null=True, upload_to='static/img/'),
        ),
    ]
