# Generated by Django 3.1.7 on 2024-06-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0010_remove_paqueteturistico_disponibles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paqueteturistico',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
    ]
