# Generated by Django 3.1.7 on 2024-06-06 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0013_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paqueteturistico',
            name='imagen',
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.paqueteturistico')),
            ],
        ),
    ]
