# Generated by Django 3.1.7 on 2024-06-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0014_auto_20240606_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='paqueteturistico',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
