# Generated by Django 3.1.7 on 2024-06-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0017_auto_20240606_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paqueteturistico',
            old_name='imagen',
            new_name='imagenTres',
        ),
        migrations.AddField(
            model_name='paqueteturistico',
            name='imagenDos',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
        migrations.AddField(
            model_name='paqueteturistico',
            name='imagenUno',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
    ]
