# Generated by Django 3.1.7 on 2024-06-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0021_cliente_fecha_nacimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='fecha_nacimiento',
            new_name='fechaFinal',
        ),
        migrations.AddField(
            model_name='cliente',
            name='fechaInicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
