# Generated by Django 3.1.7 on 2024-06-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0022_auto_20240617_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fechaFinal',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fechaInicio',
            field=models.DateField(null=True),
        ),
    ]
