# Generated by Django 3.1.7 on 2024-06-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0023_auto_20240618_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cliente',
            name='viajeros',
            field=models.CharField(choices=[('adultos', 'Adultos'), ('niños', 'Niños')], default=2, max_length=10),
            preserve_default=False,
        ),
    ]
