# Generated by Django 3.1.7 on 2024-06-19 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0024_auto_20240618_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cantidad',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='viajeros',
            field=models.JSONField(default=dict),
        ),
    ]
