# Generated by Django 3.1.7 on 2024-06-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0025_auto_20240618_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='viajeros',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
