# Generated by Django 3.1.7 on 2024-06-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0026_auto_20240618_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
