# Generated by Django 3.1.7 on 2024-06-29 23:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0034_auto_20240618_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fechaReserva',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
