# Generated by Django 3.1.7 on 2024-06-30 02:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0035_reserva_fechareserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='horaReserva',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
