# Generated by Django 3.1.7 on 2024-08-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0038_auto_20240629_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.PositiveIntegerField(max_length=11, unique=True),
        ),
    ]
