# Generated by Django 3.1.7 on 2024-08-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0039_auto_20240810_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
