# Generated by Django 3.1.7 on 2024-08-10 21:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0040_auto_20240810_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fechaInicio',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
