# Generated by Django 3.1.7 on 2024-08-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0042_auto_20240810_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fechaFinal',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fechaInicio',
        ),
        migrations.AddField(
            model_name='reserva',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fechaFinal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fechaInicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
