# Generated by Django 3.1.7 on 2024-08-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0044_cliente_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='user',
        ),
    ]
