# Generated by Django 3.1.7 on 2024-08-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0045_remove_cliente_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fechaFinal',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fechaReserva',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fechaFinal',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fechaInicio',
            field=models.DateField(null=True),
        ),
    ]
