# Generated by Django 3.1.7 on 2024-08-18 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0046_auto_20240817_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fechaFinal',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fechaInicio',
        ),
    ]
