# Generated by Django 3.1.7 on 2024-08-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0047_auto_20240817_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechasReserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField(null=True)),
                ('fechaFinal', models.DateField(null=True)),
                ('cantidad', models.IntegerField(default=1)),
            ],
        ),
    ]
