# Generated by Django 3.1.7 on 2024-08-18 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0048_fechasreserva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='fechaInicio',
            new_name='fechaReserva',
        ),
    ]
