# Generated by Django 3.1.7 on 2024-08-18 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0050_auto_20240817_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fechasreserva',
            old_name='cantidad',
            new_name='personas',
        ),
    ]
