# Generated by Django 3.1.7 on 2024-08-18 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0051_auto_20240817_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechasreserva',
            name='paquete',
            field=models.ForeignKey(default=66, on_delete=django.db.models.deletion.CASCADE, to='reservas.paqueteturistico'),
            preserve_default=False,
        ),
    ]
