# Generated by Django 3.1.7 on 2024-08-20 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0052_fechasreserva_paquete'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservas.fechasreserva'),
            preserve_default=False,
        ),
    ]
