# Generated by Django 3.1.7 on 2024-08-20 03:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0053_reserva_fecha_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fechaReserva',
            field=models.DateField(auto_now_add=True, default=datetime.date(2024, 8, 20)),
            preserve_default=False,
        ),
    ]
