# Generated by Django 3.1.7 on 2024-08-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0056_auto_20240820_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contrasena',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
