# Generated by Django 3.1.7 on 2024-08-27 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0057_cliente_contrasena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='contrasena',
        ),
    ]
