# Generated by Django 3.1.7 on 2024-08-27 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0059_cliente_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='password',
            new_name='contrasena',
        ),
    ]
