# Generated by Django 3.1.7 on 2024-09-01 03:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0060_auto_20240826_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='contrasena',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='paquete',
        ),
        migrations.AddField(
            model_name='cliente',
            name='nacionalidad',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
