# Generated by Django 3.1.7 on 2024-09-01 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0061_auto_20240831_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='paquete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='reservas.paqueteturistico'),
        ),
    ]
