# Generated by Django 3.1.7 on 2024-09-01 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0064_auto_20240831_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='paquete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.paqueteturistico'),
        ),
    ]
