# Generated by Django 3.1.7 on 2024-09-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0065_auto_20240831_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nacionalidad',
            field=models.CharField(choices=[('AR', 'Argentina'), ('BR', 'Brazil'), ('CL', 'Chile'), ('CO', 'Colombia'), ('MX', 'Mexico')], max_length=2),
        ),
    ]
