# Generated by Django 3.1.7 on 2024-09-06 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0066_auto_20240903_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaReserva', models.DateField(auto_now_add=True)),
                ('horaReserva', models.TimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.cliente')),
                ('fecha_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.fechasreserva')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.paqueteturistico')),
            ],
        ),
    ]
