# Generated by Django 3.1.7 on 2024-09-07 03:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0067_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('Cédula', 'Cédula de Ciudadanía'), ('Cédula_Extranjeria', 'Cédula de Extranjeria'), ('Tarjeta_Extranjería', 'Tarjeta de Extranjería'), ('Pasaporte', 'Pasaporte')], default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
