# Generated by Django 3.1.7 on 2024-09-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0068_cliente_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='numero_documento',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
