# Generated by Django 3.1.7 on 2024-09-07 22:01

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0069_cliente_numero_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nacionalidad',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
