# Generated by Django 3.1.7 on 2024-09-18 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0070_auto_20240907_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechasreserva',
            name='personas',
            field=models.IntegerField(default=0),
        ),
    ]
