# Generated by Django 5.1.1 on 2024-10-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0073_fechasreserva_dias_seleccionados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechasreserva',
            name='dias_seleccionados',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fechasreserva',
            name='noches_seleccionadas',
            field=models.IntegerField(default=0),
        ),
    ]
