# Generated by Django 3.1.7 on 2024-10-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0073_pqrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqrs',
            name='felicitaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='tipo',
            field=models.CharField(choices=[('peticion', 'Petición'), ('queja', 'Queja'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia'), ('felicitaciones', 'Felicitaciones')], max_length=20),
        ),
    ]
