# Generated by Django 3.1.7 on 2024-10-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0074_auto_20241006_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pqrs',
            old_name='felicitaciones',
            new_name='felicitacion',
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='tipo',
            field=models.CharField(choices=[('peticion', 'Petición'), ('queja', 'Queja'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia')], max_length=20),
        ),
    ]
