# Generated by Django 5.1.1 on 2024-10-14 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0074_alter_fechasreserva_dias_seleccionados_and_more'),
        ('reservas', '0075_auto_20241006_1719'),
    ]

    operations = [
    ]
