# Generated by Django 4.2 on 2024-10-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0076_merge_20241014_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pqrs',
            name='felicitacion',
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='tipo',
            field=models.CharField(choices=[('peticion', 'Petición'), ('queja', 'Queja'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia'), ('felicitaciones', 'Felicitacines')], max_length=20),
        ),
    ]
